#! /usr/bin/env python
# -*- coding: utf-8 -*-


"""Constants for bio NLP."""


import random

RANDOM_STATE = 42

CHATGPT_CANCER_GENES = [
    "ATAD3A",
    "CEP164",
    "ZBTB20",
    "NUP98",
    "ANKS1B",
    "CDK5",
    "DCAF13",
    "LZTR1",
    "KIF1B",
    "RABL3",
]


CLAUDE_CANCER_GENES = [
    "SIRT7",
    "CLOCK",
    "FOXO6",
    "DNMT3L",
    "HELQ",
    "NEIL3",
    "ALKBH8",
    "PNPLA7",
]


GENERAL_SEARCH_TERMS = [
    "ATAC-seq",
    "ChIA-PET",
    "DNA",
    "DNase",
    "GWAS",
    "Hi-C",
    "Pseudogene",
    "QTL",
    "RNA",
    "RNAi",
    "Repli-seq",
    "SNPs",
    "WGBS",
    "ChIP-seq",
    "chromatid",
    "chromatin",
    "eCLIP",
    "eQTL",
    "epigenetics",
    "epigenome",
    "epigenomic",
    "epigenomics",
    "gene",
    "genes",
    "genetic",
    "genetics",
    "genome",
    "genomic",
    "genomics",
    "genotype",
    "haplotype",
    "lncRNA",
    "lncRNAs",
    "mRNA",
    "methylation",
    "noncoding",
    "phenotype",
    "polymerase",
    "proteome",
    "retrotransposon",
    "sRNAs",
    "telomerase",
    "transcription",
    "transcriptional",
    "transcriptome",
    "transcriptomic",
    "transcriptomics",
    "transposon",
    "tRNA",
    "{allele}",
    "{chromatin modification}",
    "{3D chromatin interactions}",
    "{DNA accessibility}",
    "{DNA condensation}",
    "{DNA damage}",
    "{DNA elements}",
    "{DNA polymerase}",
    "{DNA repair}",
    "{DNA replication}",
    "{DNA sequencing}",
    "{DNA supercoiling}",
    "{RNA decay}",
    "{RNA interference}",
    "{RNA modification}",
    "{RNA polymerase}",
    "{RNA processing}",
    "{RNA replication}",
    "{chromatin remodeling}",
    "{chromatin states}",
    "{chromosome condensation}",
    "{chromosome segregation}",
    "{cis-regulatory}",
    "{copy number variation}",
    "{distal enhancers}",
    "{dna damage}",
    "{dna recombination}",
    "{functional genomics}",
    "{gene expression}",
    "{gene function}",
    "{genetic mutation}",
    "{gene regulation}",
    "{gene regulatory network}",
    "{genetic mechanism}",
    "{genome sequencing}",
    "{histone}",
    "{long non-coding RNA}",
    "{massively parallel reporter assays}",
    "{massively parallel sequencing}",
    "{messenger RNA}",
    "{microRNA}",
    "{noncoding elements}",
    "{next generation sequencing}",
    "{open chromatin}",
    "{origin of replication}",
    "{polyA RNA}",
    "{post-transcriptional modification}",
    "{post-translational modification}",
    "{protein activation}",
    "{protein coding}",
    "{protein decay}",
    "{protein modification}",
    "{protein translation}",
    "{protein-coding}",
    "{regulatory element}",
    "{regulatory elements}",
    "{repeat DNA}",
    "{repetitive DNA}",
    "{RNA binding}",
    "{segmental duplication}",
    "{short hairpin RNA}",
    "{single nucleotide polymorphism}",
    "{small RNA}",
    "{small inhibitory RNA}",
    "{tandem repeat}",
    "{topologically associating domains}",
    "{trans-regulatory}",
    "{transcription factors}",
    "{transcription factor}",
    "{transcriptional modification}",
    "{transcriptional regulation}",
    "{transcriptional regulation}",
    "{translational modification}",
    "{translational regulation}",
]


TEST_SET_JOURNALS = [
    "American Journal of Human Genetics",
    "Human Genetics",
    "Human Molecular Genetics",
    "European Journal of Human Genetics",
]


SUBLIST_INITIAL = [
    "( All|All) (rights of any nature whatsoever reserved.|rights of reproduction in any form reserved.|rights rights reserved.|rights reserved.|rights reserved|rights resreved.|rights reseserved.|rights reseved.|rights received.|rights reserve.|rights.|rights)",
    "(, some| some) (rights reserved|rights reserved;)",
    "(Published with license by Taylor  &  Francis)( Group, LLC. | Group, LLC |. | )",
]
SUBLIST_TOKEN_ZERO = [
    '(^© ([0-9]*))(.*?)([a-z0-9A-Z!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+)',
    '(^©([0-9]*))(.*?)([a-z0-9A-Z!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+)',
]
SUBLIST_TOKEN_ONE = [
    '^Copyright(.*?)© ([0-9]*)(.*?)([a-z0-9A-Z!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+)',
    '^Copyright(.*?)©([0-9]*)(.*?)([a-z0-9A-Z!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+)',
    '^, Copyright(.*?)©([0-9]*)(.*?)([a-z0-9A-Z!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+\ [a-z0-9!@#$&()\\-`+,/"]+)',
]
SUBLIST_POST = [
    "^[A-Z]{1}[a-z]+ et al\. ",
    "This is an open access article distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited. ",
    "Limited, trading as Taylor  &  Francis Group. ",
    "<.{3}>",
    "</.{3}>",
]
SUBLIST_TITLE = ["<.{3}>", "</.{3}>"]

FILTER_TERMS = [
    "promoter",
    "enhancer",
    "transcription factor",
    "transcriptional regulator",
    "transcriptional repressor",
    "gene",
    "protein",
    "transcript",
    "chromatin",
    "chromosome",
    "mRNA",
    "DNA",
    "RNA",
    "mechanism",
    "mechanisms",
    "messenger",
    "signaling",
    "signal",
    "pathway",
    "pathways",
    "receptor",
    "receptors",
    "cell",
    "cells",
    "cellular",
    "eQTL",
    "QTL",
    "ChIP",
    "epigenomic",
    "epigenome",
    "lncRNA",
    "noncoding",
    "polymerase",
    "retrotransposon",
    "telomerase",
    "transcription",
    "transcriptional",
    "transcriptome",
    "transposon",
    "DNA accessibility",
    "DNA damage",
    "DNA element" "DNA methylation",
    "DNA repair",
    "DNA sequence",
    "DNA structure",
    "3D chromatin",
    "3D genome",
    "chromatin accessibility",
    "cis-regulatory element",
    "chromatin conformation",
    "chromatin domain",
    "chromatin loop",
    "chromatin modification",
    "chromatin organization",
    "histone",
    "histone modification",
    "histone variant",
    "nucleosome",
    "H3K4me3",
    "H3K27ac",
    "H3K27me3",
    "H3K36me3",
    "H3K4me1",
    "microRNA",
    "post-translational modification",
    "protein complex",
    "noncoding elements",
    "noncoding RNA",
    "noncoding RNAs",
    "super enhancer",
    "super-enhancer",
    "super-enhancers",
    "transcriptional modification",
    "transcriptional regulation",
    "transcriptional regulator",
    "transcriptional repressor",
    "cell function",
    "cell type",
    "cell types",
    "cellular function",
    "biological process",
    "biological processes",
    "cellular component",
    "biological mechanism",
    "biological mechanisms",
    "biological pathway",
    "multicellular organism",
    "multicellular organisms",
    "eukaryotic",
    "vertebrate",
    "signaling pathway",
    "signaling pathways",
    "mammalian",
    "human",
    "humans",
    "tissue",
    "tissues",
    "tissue-specific",
    "tissue-specificity",
    "tissue-specific expression",
    "controlling",
    "target",
    "targets",
    "targeting",
    "targeted",
    "cell",
    "key role",
    "genome regulation",
    "structural variation",
    "polymorphism",
    "gene expression",
    "gene expression regulation",
    "activated",
    "key signaling",
    "key role",
    "key roles",
    "key function",
    "genome structure",
    "genome organization",
    "genome regulation",
    "genome-wide",
    "genome-wide association",
    "genome-wide association study",
    "critical roles",
    "biological functions",
    "biological function",
    "biological processes",
    "biological process",
    "biological mechanisms",
    "gene target",
    "gene targets",
    "core human",
    "core promoter",
    "loss",
    "loss of function",
    "inhibitor",
    "inhibits",
    "role",
    "function",
    "contribution",
    "critical",
    "involved",
    "evidence",
    "lacked",
    "present",
    "precise",
    "process",
    "explored",
    "demonstrated",
    "proposed",
    "involvement",
    "down-regulated",
    "down-regulation",
    "regulates",
]

SPECIFIC_TERMS = [
    "central dogma",
    "gene expression",
    "mRNA",
    "mRNA stability",
    "DNA replication",
    "transcription",
    "translation",
    "transcriptional regulation",
    "reverse transcription",
    "RNA replication",
    "post-translational modification",
    "methylation",
    "epigenetic",
    "model",
    "models",
    "cell cycle",
    "regulator",
    "mechanism",
    "mammalian",
    "human",
    "histones",
    "chromatin",
    "promoter",
    "enhancer",
    "required",
    "necessary",
    "essential",
    "dependent",
]

COPY_GENES = {
    "WAS": "wasgene",
    "SHE": "shegene",
    "IMPACT": "impactgene",
    "MICE": "micegene",
    "REST": "restgene",
    "SET": "setgene",
    "MET": "metgene",
    "GC": "gcgene",
    "ATM": "atmgene",
    "MB": "mbgene",
    "PIGS": "pigsgene",
    "CAT": "catgene",
    "COIL": "coilgene",
}


SUBLIST = [
    "\[Figure not available\: see fulltext.\]\.",
    "(Authors [0-9][0-9][0-9][0-9],|Author\(s\) [0-9][0-9][0-9][0-9],|Author\(s\), [0-9][0-9][0-9][0-9]| Group, a division of|)( under exclusive licence to|[0-9][0-9][0-9][0-9]|) Macmillan Publishers (Ltd|Limited, part of Springer Nature|Limited)",
    "Copyright [0-9][0-9][0-9][0-9] by Annual Reviews. ",
    " Biological Reviews",
    "(Copyright [0-9][0-9][0-9][0-9] by the|Copyright [0-9][0-9][0-9][0-9] the|Copyright [0-9][0-9][0-9][0-9]|exclusive licensee) American Association for the Advancement of Science.",
    "Elsevier (Science Inc.|Science|)",
    "Copyright \(C\) [0-9][0-9][0-9][0-9]",
    "Copyright [0-9][0-9][0-9][0-9]",
    "\(C\) [0-9][0-9][0-9][0-9]",
    "Proceedings of the National Academy of Sciences of the United States of America",
    "National Academy of Sciences",
    "The (Author\(s\)|Authors|Author) [0-9][0-9][0-9][0-9]\. ",
    "This article is an open access article distributed under the terms and conditions of the Creative Commons Attribution \(CC BY\) license \(http://creativecommons.org/licenses/by/4.0/\), ",
    "This article is an open access article distributed under the terms and conditions of the Creative Commons Attribution \(CC BY\) license \(http://creativecommons.org/licenses/by/4.0/\)",
    "This( article| )is an (Open Access|Open-Access|open-access|open access) article (distributed under|under)( the CC BY-NC-ND license \(http://creativecommons.org/licenses/by-nc-nd/4.0/\)|  the CC BY license \(http://creativecommons.org/licenses/by/3.0/\).| |)the terms of the Creative (Commons|Commns) (Attribution Non-Commercial |Attribution |)License \(http(s|)://( creativecommons|creativecommons).org/( |)licenses/(by-nc-nd|by-nc|by)/(2.5|2.0|3.0|4.0|[0-9]\.[0-9]|[0-9]\. [0-9])(/uk/|/|)\)(, | |.|)(which permits unrestricted non-commercial use, distribution, and reproduction in any medium, provided the original work is properly cited|which permits unrestricted non-commercial use, distribution, and reproduction in any medium, provided the original work is properly cited attributed| |)(\.|\,| |)",
    "http://creativecommons.org/licenses/by/4.0/",
    "This article is distributed under the terms of the Creative Commons Attribution 4.0 International License (), which permits unrestricted use, distribution, and reproduction in any medium, provided you give appropriate credit to the original author(s) and the source, provide a link to the Creative Commons license, and indicate if changes were made. The Creative Commons Public Domain Dedication waiver \(http://creativecommons.org/publicdomain/zero/1.0/\) applies to the data made available in this article, unless otherwise stated.",
    "et al.; licensee BioMed Central Ltd. which permits unrestricted use, distribution, and reproduction in any medium, provided the original work is properly credited. The Creative Commons Public Domain Dedication waiver \(http://creativecommons.org/publicdomain/zero/1.0/\) applies to the data made available in this article, unless otherwise stated.",
    "This is an open (access article|article) (distributed under|under) the (terms if the Creative Commons Attribution Non-Commercial License|)(CC BY-NC-ND|CC BY-NC|\(CC BY-NC\)|CC BY|)( license | |)\(http://creativecommons.org/licenses/by-nc-nd/4.0/\)",
    "This article is distributed under the terms of the Creative Commons Attribution 4.0 International License \(\), which permits unrestricted use, distribution, and reproduction in any medium, provided you give appropriate credit to the original author\(s\) and the source, provide a link to the Creative Commons license, and indicate if changes were made. The Creative Commons Public Domain Dedication waiver \(http://creativecommons.org/publicdomain/zero/1.0/\) applies to the data made available in this article, unless otherwise stated.",
    "This is an open access article distributed under the terms of the Creative Commons Attribution \(CC BY-NC\) license \(https://creativecommons.org/licenses/by-nc/4.0/\).",
    "After six months it is available under a Creative Commons License \(Attribution-Noncommercial-Share Alike 4\.0 International license, as described at https://creativecommons.org/licenses/by-nc-sa/4.0/\)",
    "This is an article distributed under the terms of the Creative Commons Attribution Non-Commercial License \(http://creativecommons.org/licenses/by-nc-nd/4.0/\)",
    "video abstract",
    "Office in association with Oxford University Press.*?\.",
    "Published by Oxford University Press.*?\.",
    " Oxford University Press",
    "Proc. Natl. Acad. Sci.",
    "Published by Cold Spring Harbor Laboratory Press.( |)",
    "[a-zA-Z]+ published by Wiley Periodicals, Inc. on behalf.*?\.",
    "[a-zA-Z]+ published by Wiley Periodicals, Inc.",
    "Wiley Periodicals, Inc",
    "et al.",
    "This is a U.S. government work and not under copyright protection in the U.S(.|); foreign copyright protection may apply.",
    "Limited, part of Springer Nature.",
    " , part of Springer Nature.",
    " LLC, part of Springer Nature.",
    " Germany, part of Springer Nature.",
    " Author\(s\), under exclusive licence to Springer Nature America, Inc.",
    " Author\(s\), under exclusive licence to Springer Nature Limited.",
    " ., part of Springer Nature.",
    " KK, part of Springer Nature.",
    "Austria, part of Springer Nature.",
    "AG, part of Springer Nature.",
    " SAS, part of Springer Nature.",
    " \(C\) [0-9][0-9][0-9][0-9] by The American Society of Hematology.",
    " Official journal of the American Society of Gene  &  Cell Therapy",
    "  by The American Society of Hematology.",
    "Published under exclusive license by The American Society for Biochemistry and Molecular Biology, Inc.",
    "Transplantation and the American Society of Transplant Surgeons",
    "This article is distributed by The American Society for Cell Biology under license from the author\(s\).",
    "[a-zA-Z]+ published by John Wiley  &  Sons.*?\.",
    "; licensee Biomed Central( Ltd.|.)",
    "( |)(For permissions|For Permissions|Permissions)(,|) please email: (J|j)ournals.permissions(@oup.com.|@oxfordjournals.org.)",
    "For any queries, please email at epub@benthamscience.org.",
    "For any queries, please email at epub@benthamscience.net.",
    "http[s]?://[^\s]+[^.( \n)]",
    "www[^\s]+[^.( \n)]",
    "�",
    "wiley periodicals inc",
    "This is an open access article distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.",
]


census_oncogenes = [
    "a1cf",
    "abl1",
    "abl2",
    "ackr3",
    "acvr1",
    "afdn",
    "aff3",
    "aff4",
    "akt1",
    "akt2",
    "akt3",
    "alk",
    "apobec3b",
    "ar",
    "araf",
    "arhgap5",
    "arnt",
    "atf1",
    "atp1a1",
    "bcl11a",
    "bcl11b",
    "bcl2",
    "bcl2l12",
    "bcl3",
    "bcl6",
    "bcl9",
    "bcl9l",
    "bcorl1",
    "birc3",
    "birc6",
    "bmpr1a",
    "braf",
    "brd3",
    "brd4",
    "btk",
    "cacna1d",
    "calr",
    "card11",
    "cbl",
    "cblb",
    "cblc",
    "ccnd1",
    "ccnd2",
    "ccnd3",
    "ccne1",
    "ccr4",
    "ccr7",
    "cd28",
    "cd74",
    "cd79a",
    "cd79b",
    "cdh17",
    "cdk4",
    "cdk6",
    "cdkn1a",
    "chd4",
    "chst11",
    "cic",
    "creb1",
    "creb3l2",
    "crebbp",
    "crlf2",
    "crtc1",
    "csf1r",
    "csf3r",
    "ctnna2",
    "ctnnb1",
    "ctnnd2",
    "cux1",
    "cxcr4",
    "cysltr2",
    "daxx",
    "ddb2",
    "ddit3",
    "ddr2",
    "ddx5",
    "ddx6",
    "dek",
    "dgcr8",
    "egfr",
    "elf4",
    "elk4",
    "epas1",
    "erbb2",
    "erbb3",
    "erbb4",
    "erg",
    "esr1",
    "etv1",
    "etv4",
    "etv5",
    "ewsr1",
    "ezh2",
    "fcgr2b",
    "fcrl4",
    "fes",
    "fev",
    "fgfr1",
    "fgfr1op",
    "fgfr2",
    "fgfr3",
    "fgfr4",
    "fli1",
    "flt3",
    "flt4",
    "foxa1",
    "foxl2",
    "foxo1",
    "foxo3",
    "foxo4",
    "foxp1",
    "foxr1",
    "fstl3",
    "fubp1",
    "gata1",
    "gata2",
    "gata3",
    "gli1",
    "gna11",
    "gnaq",
    "gnas",
    "gpc3",
    "grm3",
    "h3f3a",
    "h3f3b",
    "hey1",
    "hgf",
    "hif1a",
    "hip1",
    "hist1h3b",
    "hlf",
    "hmga1",
    "hmga2",
    "hnrnpa2b1",
    "hoxa11",
    "hoxa13",
    "hoxa9",
    "hoxc11",
    "hoxc13",
    "hoxd11",
    "hoxd13",
    "hras",
    "idh1",
    "idh2",
    "ikbkb",
    "ikzf3",
    "il6st",
    "il7r",
    "irf4",
    "irs4",
    "jak1",
    "jak2",
    "jak3",
    "jun",
    "kat6a",
    "kat7",
    "kcnj5",
    "kdm5a",
    "kdm6a",
    "kdr",
    "kit",
    "klf4",
    "kmt2a",
    "kmt2d",
    "knstrn",
    "kras",
    "lck",
    "lef1",
    "lmo1",
    "lmo2",
    "lpp",
    "lyl1",
    "lyn",
    "macc1",
    "maf",
    "mafb",
    "malat1",
    "malt1",
    "maml2",
    "map2k1",
    "map2k2",
    "map2k4",
    "map3k1",
    "map3k13",
    "mapk1",
    "mdm2",
    "mdm4",
    "mecom",
    "met",
    "mitf",
    "mllt10",
    "mn1",
    "mpl",
    "mrtfa",
    "msi2",
    "mtcp1",
    "mtor",
    "muc16",
    "muc4",
    "myb",
    "myc",
    "mycl",
    "mycn",
    "myd88",
    "myod1",
    "ncoa2",
    "nfatc2",
    "nfe2l2",
    "nfkb2",
    "nkx2-1",
    "notch1",
    "notch2",
    "npm1",
    "nr4a3",
    "nras",
    "nsd2",
    "nsd3",
    "nt5c2",
    "ntrk1",
    "ntrk2",
    "ntrk3",
    "nup98",
    "nutm1",
    "olig2",
    "p2ry8",
    "pabpc1",
    "pax3",
    "pax5",
    "pbx1",
    "pdcd1lg2",
    "pdgfb",
    "pdgfra",
    "pdgfrb",
    "pik3ca",
    "pik3cb",
    "pim1",
    "plag1",
    "plcg1",
    "polq",
    "pou2af1",
    "pou5f1",
    "ppm1d",
    "prdm16",
    "prex2",
    "prkaca",
    "prkar1a",
    "psip1",
    "ptk6",
    "ptpn11",
    "qki",
    "rac1",
    "rad21",
    "raf1",
    "rap1b",
    "rap1gds1",
    "rara",
    "recql4",
    "rel",
    "ret",
    "rhoa",
    "ros1",
    "rras2",
    "rspo3",
    "runx1",
    "runx1t1",
    "sall4",
    "set",
    "setbp1",
    "setdb1",
    "sf3b1",
    "sgk1",
    "sh3gl1",
    "six1",
    "six2",
    "ski",
    "smo",
    "snd1",
    "sox2",
    "src",
    "srsf2",
    "srsf3",
    "ssx1",
    "ssx2",
    "ssx4",
    "stat3",
    "stat5b",
    "stat6",
    "stil",
    "suz12",
    "syk",
    "taf15",
    "tal1",
    "tal2",
    "tbl1xr1",
    "tbx3",
    "tcf3",
    "tcf7l2",
    "tcl1a",
    "tec",
    "tert",
    "tet1",
    "tfe3",
    "tfeb",
    "tlx1",
    "tlx3",
    "tmsb4x",
    "tnc",
    "tnfrsf17",
    "tp53",
    "tp63",
    "trim24",
    "trim27",
    "trrap",
    "u2af1",
    "ubr5",
    "usp6",
    "usp8",
    "was",
    "wt1",
    "wwtr1",
    "xpo1",
    "zeb1",
    "znf521",
]

subset_oncogenes = random.sample(census_oncogenes, 20)
